version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: movies-api-node
    container_name: movies-api-node
    ports:
      - '8000:8000'
    restart: on-failure
